@startuml UC20：商品一覧機能
!include ../classifiers.pu
skinparam style strictuml
hide unlinked
title UC20：商品一覧機能

== UC20 商品一覧表示 ==
autonumber 20.1
group Springフレームワーク
	itemController -> categoryRepository: @Autowired
	activate categoryRepository
	autonumber stop
	return categoryRepository
	autonumber resume
	itemController -> itemRepository: @Autowired
	activate itemRepository
	autonumber stop
	return itemRepository
	autonumber resume
end group

user -> itemController: [GET] /items[?categoryId=xx]\n items([categoryId: Integer], model: Model)
activate itemController

itemController -> categoryRepository: findAll()
activate categoryRepository

	group Springフレームワーク
		autonumber stop
		categoryRepository -> db: SELECT * FROM categories
		categoryRepository <-- db: ResultSet
		categoryRepository -> list: new ArrayLisyt<Category>()
		activate list
		return categoryList

		loop カテゴリーリストのレコード件数分
			categoryRepository -> category: new Category(id, name)
			activate category
			return category
			categoryRepository -> categoryRepository: categoryList.add(category)
		end loop
		autonumber resume
	end group

autonumber stop
return categoryList
autonumber resume
itemController -> itemController: model.addAttribute("categoryList", categoryList)

alt categoryIdが送信されない場合
	itemController -> itemRepository: findAll()
	activate itemRepository
else categoryIdが送信された場合
	itemController -> itemRepository: findByCategoryId(categoryId)
end alt

'itemController -> itemRepository: findByCategoryId(categoryId)
activate itemRepository
	group Springフレームワーク
		autonumber stop
		alt categoryIdが送信されない場合
			itemRepository -> db: SELECT * items
		else categoryIdが送信された場合
			itemRepository -> db: SELECT * items WHERE category_id = ?
		end alt
		itemRepository <-- db: ResultSet
		itemRepository -> list: new ArrayList<Item>()
		activate list
		return itemList

		loop 商品リストのレコード件数分
			itemRepository -> item: new Item(id, categoryId, name, priced)
			activate item
			return item
			itemRepository -> itemRepository: itemList.add(item)
		end loop
		autonumber resume
	end group
autonumber stop
itemController <-- itemRepository: itemList
autonumber resume
itemController -> itemController: model.addAttribute("itemList", itemList)

user <-- itemController: [view]items

@enduml




@enduml
